uploads = []
outputs = []

[[generated]]
id = "HeEk24iNPOrQbYodDQzaI"
uri = "file://artifacts/rejouice-clone/src/assets/images/nexus.png"
type = "image"
title = "Brand photography nexus"

[[generated]]
id = "9Nc4jKavIEj-EDoMiQJf0"
uri = "file://artifacts/rejouice-clone/src/assets/images/aurora.png"
type = "image"
title = "Brand photography aurora"

[[generated]]
id = "0wHG0f95zXHIl5ebz7dnR"
uri = "file://artifacts/rejouice-clone/src/assets/images/vertex.png"
type = "image"
title = "Brand photography vertex"

[[generated]]
id = "Vwv_WwnM58P2ClHPyoKxU"
uri = "file://artifacts/rejouice-clone/src/assets/images/lumis.png"
type = "image"
title = "Brand photography lumis"

[[generated]]
id = "XeaGQraLyfL_kh7slx0Xu"
uri = "file://artifacts/beyond-company-profile/public/cover-hero.png"
type = "image"
title = "generated_image"
